# Generated by Django 3.0.2 on 2020-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_body', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
